# Generated by Django 4.2.14 on 2024-11-06 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['-created_at'],
                'permissions': [('can_view', 'Can view something'), ('can_edit', 'Can edit something')],
            },
        ),
        migrations.CreateModel(
            name='BuyerPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('can_add_group', models.BooleanField(default=False)),
                ('can_change_group', models.BooleanField(default=False)),
                ('can_delete_group', models.BooleanField(default=False)),
                ('can_view_group', models.BooleanField(default=False)),
                ('can_add_policy', models.BooleanField(default=False)),
                ('can_change_policy', models.BooleanField(default=False)),
                ('can_delete_policy', models.BooleanField(default=False)),
                ('can_add_seller_user', models.BooleanField(default=False)),
                ('can_change_seller_user', models.BooleanField(default=False)),
                ('can_delete_seller_user', models.BooleanField(default=False)),
                ('buyer_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('can_add_log_entry', models.BooleanField(default=False)),
                ('can_change_log_entry', models.BooleanField(default=False)),
                ('can_delete_log_entry', models.BooleanField(default=False)),
                ('can_view_log_entry', models.BooleanField(default=False)),
                ('can_add_group', models.BooleanField(default=False)),
                ('can_change_group', models.BooleanField(default=False)),
                ('can_delete_group', models.BooleanField(default=False)),
                ('can_view_group', models.BooleanField(default=False)),
                ('can_add_permission', models.BooleanField(default=False)),
                ('can_change_permission', models.BooleanField(default=False)),
                ('can_delete_permission', models.BooleanField(default=False)),
                ('can_view_permission', models.BooleanField(default=False)),
                ('can_add_content_type', models.BooleanField(default=False)),
                ('can_add_product', models.BooleanField(default=False)),
                ('can_change_product', models.BooleanField(default=False)),
                ('can_delete_product', models.BooleanField(default=False)),
                ('can_view_product', models.BooleanField(default=False)),
                ('can_view_category', models.BooleanField(default=False)),
                ('can_add_color', models.BooleanField(default=False)),
                ('can_change_color', models.BooleanField(default=False)),
                ('can_delete_color', models.BooleanField(default=False)),
                ('can_view_color', models.BooleanField(default=False)),
                ('can_add_image', models.BooleanField(default=False)),
                ('can_change_image', models.BooleanField(default=False)),
                ('can_delete_image', models.BooleanField(default=False)),
                ('can_view_image', models.BooleanField(default=False)),
                ('seller_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=50)),
                ('image', models.BinaryField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(blank=True, max_length=50)),
                ('street_address', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('second_phone_number', models.CharField(blank=True, max_length=13)),
                ('building_number', models.CharField(blank=True, max_length=50)),
                ('apartment_number', models.CharField(blank=True, max_length=50)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.sellerpolicy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_permissions', to='auth.permission')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='auth.permission')),
                ('policies', models.ManyToManyField(blank=True, related_name='groups', to='user.policy')),
            ],
            options={
                'db_table': 'group',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyerUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.BinaryField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(blank=True, max_length=50)),
                ('street_address', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('second_phone_number', models.CharField(blank=True, max_length=13)),
                ('building_number', models.CharField(blank=True, max_length=50)),
                ('apartment_number', models.CharField(blank=True, max_length=50)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.buyerpolicy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='user.group'),
        ),
        migrations.AddField(
            model_name='user',
            name='policies',
            field=models.ManyToManyField(blank=True, related_name='users', to='user.policy'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
