# Generated by Django 4.2.14 on 2024-11-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='permissions',
        ),
        migrations.AddField(
            model_name='group',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='group_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='policy',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='policy_permissions', to='auth.permission'),
        ),
    ]
