# Generated by Django 4.2.14 on 2024-11-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_group_permissions_remove_policy_permissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='policy',
            table='policy',
        ),
    ]
