# Generated by Django 4.2.14 on 2024-12-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telephone_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
