# Generated by Django 4.2.14 on 2024-12-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_order_amount_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
