# Generated by Django 4.2.14 on 2024-12-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_remove_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
