# Generated by Django 4.2.14 on 2024-12-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_coupon_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_uses',
            field=models.IntegerField(null=True),
        ),
    ]
